Milestone 2
marcode95/calculator pull request #2
Opened 2021-06-24 12:17 UTC by marcode95

-created four components: app, button, buttonpanel, display
-display is accepting result as incoming prop
-button is accepting name as incoming prop
-buttonpanel is rendering five button groups buttons

2021-06-24 14:38 UTC, mimipeshy commented
## STATUS : CHANGES REQUESTED 🔴 ♻️ 
Hello @vidhishweta01 👋🏾 👋🏾 congratulations on making it this far 😄 . 

#### Highlights

- You have communicated why you have not configured linters, ensure you have the meeting with the TSE. Hope to see them working soon ✔️
-  

#### To improve
Let's improve in the following areas ⬇️ 
- [ ] Check out my inline comments

That's all 😄, kindly submit another review when done
If you need any clarification, kindly post your comment here and tag me @mimipeshy and will be glad to help

Regards,
Peris Ndanu

2021-06-24 14:40 UTC, mimipeshy commented on src/components/App.js
> +      <ButtonPanel />
- [ ] components should be wrapped in [React.Fragment](https://reactjs.org/docs/fragments.html#short-syntax) short syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/ReactFragment.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896092/))

2021-06-24 14:42 UTC, mimipeshy commented on src/components/Display.js
> +};
- [ ] `result` should be the incoming prop ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/incomingProps.png)). Then in line 7 just call  {result}

2021-06-24 14:44 UTC, mimipeshy commented on src/components/Button.js
> +};
- [ ] it accepts `a button name` as an incoming prop ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/button/acceptProp.png)). In line 7 just call {buttonName}

2021-06-24 14:48 UTC, mimipeshy commented on src/components/Button.js
> +  name: PropTypes.string, // eslint-disable-line
- [ ] Change line 13 to `name: PropTypes.string.isRequired`

2021-06-24 18:02 UTC, Forison requested changes
# Status::Change Required❌

## Hello @marcode95 

#### Good job on addressing the some of the issues raised in the previous review, you did well refactoring the component by destructuring the `props` at the argument level. However there is another issue that arose from our type checking  other issue we need address well before we proceed🤗.

#### Check my comments below👇

#### Happy coding

Addo Forison

2021-06-24 18:02 UTC, Forison commented on src/components/Button.js
> +  buttonName: PropTypes.string.isRequired, // eslint-disable-line
* [x] Adding `isRequired` to this prop validation will throw an error in the browser console because of the failing type, For this component if you decide to go for the `isRequired` option we have to set default prop type. Else remove the `isRequired` attribute. We don't really want a default props for this component.

2021-06-24 18:02 UTC, Forison commented on src/components/ButtonPanel.js
> +const ButtonPanel = () => { // eslint-disable-line
**[optional]**
Do not modify linter rules, by doing so you miss out on the goal, that particular rules seeks to teach you. Here you are trying to disable the javascript `eval()` which when disabled and misused can exposed your code to serious injection attacks. [2](https://masteringjs.io/tutorials/eslint/ignore), [2](https://eslint.org/docs/rules/no-eval)

2021-06-25 12:16 UTC, uche-inyama approved these changes
## Approved

### Hi Marco Erhardt :slightly_smiling_face: 

We are good here, you can move on with the next milestone.

### Happy coding :man_technologist: 

#### ``` Uchechukwu Henry Inyama ```

2021-06-25 16:15 UTC, merged